apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    run: my-app
spec:
  selector:
    app: app-deployment
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  type: LoadBalancer